services:
  - type: web
    name: home-inventory-app
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
    autoDeploy: true
